### ISSUE TITLE
Why not fork Framework7?

### ISSUE THREAD

**Issue by DanRioDev** [JedWatson/touchstonejs#12]
Hi There people, how you all doing?

Ever heard of http://www.idangero.us/framework7/ ?
Is already pretty much what you guys are trying to achieve, without ReactJS.
You say "but that's the important part!" i know i know, but 'cmon, Framework7 already have most of the visual and scaffolding API already done and all that jazz.

What do you think?

**Comment by dur41d** [comment]
Framework7 is currently the best in the market in terms of UX for hybrid apps. Other frameworks may use better technology or underlying architecture but are behind in terms of UX features (I wouldn't hesitate to say "way" behind).

Unfortunately using Framework7 feels like using jquery and many have asked Framework7 to support React. The status quo is that there is a gap in the hybrid app framework market where on one side there is Framework7 with excellent UX and old technology and TouchstoneJS with new technology and inadequate UX and there is pressure by developers on both sides to fill this gap as evident in this thread.

Filling this gap is matter of time but I hope that there is a cooperation between the 2 sides so that it get's filled quicker and better.
