### ISSUE TITLE
Any contribution guide?

### ISSUE THREAD

**Issue by SaitoWu** [JedWatson/touchstonejs#30]
I saw the css code has instability coding styles, like:

```css
/* "normal" */
.list-item {
  ...
}

/* uppercase */
.Keypad {
  ...
}

/* double hyphen */
.panel--first {
  ...
}
```

I think its weird, maybe it need some reformat. Or that is a coding style in somewhere?

**Comment by BerkeleyTrue** [comment]
looks like it is trying to follow BEM practices (except for the casing). Maybe thats it.

**Comment by jossmac** [comment]
The pascal casing is used for components, I think this is the way to go as it's super obvious what is being targeted and won't conflict with other/existing styles in the app; CSS being case-sensitive.

Regarding the BEM syntax - For a while I was truly enamoured by it, since then i'm not so sure about it's helpfulness. I intend to eventually tidy up the styles.

In any case we'll likely go with some form of JSCSS. Check out https://speakerdeck.com/vjeux/react-css-in-js
